[workspace]
authors = ["Lukasz Czerniawski <l.czerniawski@icloud.com>"]
channels = [
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge",
]
name = "uuid"
description = "A high-performance Mojo library for generating, parsing, validating, and formatting UUID values in RFC-9562 compatible string forms."
license = "MIT"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
readme = "README.md"
version = "1.1.0"

[tasks]
build = "mojo package src/uuid -o uuid.mojopkg"
test = "sh scripts/run_tests.sh"
format = "mojo format src/uuid"
build_rattler = "rattler-build build --recipe conda.recipe/recipe.yaml -c https://conda.modular.com/max -c https://repo.prefix.dev/modular-community -c conda-forge"

[dependencies]
mojo = ">=1.0.0b1,<2"
crypto = ">=0.1.0,<0.2"
